from src.graph.state import ResearchState
from langchain_core.messages import AIMessage


def writer_node(state: ResearchState) -> dict:
    # Phase 2: replace with real LLM synthesis of findings into markdown report
    findings = "\n".join(state.get("research_findings", []))
    report = f"## Research Report: {state['query']}\n\n{findings}\n\n*Generated by stub writer.*"
    return {
        "final_report": report,
        "sources": ["stub-source-1", "stub-source-2"],
        "messages": [AIMessage(content="Writer: report complete.")],
    }